apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: slackbot-service
  replicas: 1
  template:
    metadata:
      labels:
        run: slackbot-service
    spec:
      containers:
      - name: slackbot-service
        image: keptncontrib/slackbot-service:latest
        imagePullPolicy: Always
        env:
        - name: keptn_host
          value: "http://api.keptn.svc.cluster.local"
        - name: keptn_api_token
          value: ""
        - name: slackbot_token
          value: ""
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: slackbot-service
  namespace: keptn
  labels:
    run: slackbot-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: slackbot-service
