apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: slackbot-service
  replicas: 1
  template:
    metadata:
      labels:
        run: slackbot-service
    spec:
      containers:
      - name: slackbot-service
        image: keptnsandbox/slackbot-service:latest
        imagePullPolicy: Always
        env:
        - name: keptn_host
          value: "http://api-gateway-nginx.keptn.svc.cluster.local"
        - name: bridge_url
          value: ""
        - name: keptn_api_token
          valueFrom:
            secretKeyRef:
              name: keptn-api-token
              key: keptn-api-token
        - name: slackbot_token
          valueFrom:
            secretKeyRef:
              name: slackbot
              key: slackbot-token
        - name: slack_webhook
          valueFrom:
            secretKeyRef:
              name: slackbot
              key: slack-webhook
        - name: slack_channel
          valueFrom:
            secretKeyRef:
              name: slackbot
              key: slack-channel
        ports:
        - containerPort: 8080
        - containerPort: 5000
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: distributor
        image: keptn/distributor:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 10999
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PUBSUB_URL
            value: 'nats://keptn-nats-cluster'
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.event.approval.triggered'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
          - name: PUBSUB_RECIPIENT_PORT
            value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: slackbot-service
  namespace: keptn
  labels:
    run: slackbot-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: slackbot-service
---
apiVersion: v1
kind: Service
metadata:
  name: slackbot-external
  namespace: keptn
  labels:
    run: slackbot-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    run: slackbot-service
